import { SET_MESSAGE_ACTIVE_USER, RESET_MESSAGE_ACTIVE_USER } from './reducers/talk'
import { ADD_MESSAGE, SET_MESSAGE } from './reducers/messages'
import { INCREMENT_NOTIFICATION_MESSAGE, RESET_COUNTER_MESSAGE } from './reducers/notifications'

export default {
    SET_MESSAGE_ACTIVE_USER,
    RESET_MESSAGE_ACTIVE_USER,
    ADD_MESSAGE,
    SET_MESSAGE,
    INCREMENT_NOTIFICATION_MESSAGE,
    RESET_COUNTER_MESSAGE
    
}